FROM python:3.12-alpine

RUN addgroup -S djangogroup && adduser -S djangouser -G djangogroup

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . .

RUN chown -R djangouser:djangogroup /app

USER djangouser

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]